---
- name: Restart bind9
  ansible.builtin.service:
    name: bind9
    state: restarted

- name: Reload bind9
  ansible.builtin.service:
    name: bind9
    state: reloaded

- name: Restart monit
  ansible.builtin.service:
    name: monit
    state: restarted

- name: Zone file change
  ansible.builtin.debug:
    msg: "dummy handler"
