---
roles:
  - src: geerlingguy.docker
    version: 7.1.0
  - src: geerlingguy.pip
    version: 3.0.3
  - src: geerlingguy.ntp
    version: 2.4.0
  - src: geerlingguy.postgresql
    version: 3.5.0
  - src: oefenweb.locales
    version: v1.0.52
  - src: geerlingguy.node_exporter
    version: 2.1.0
  - src: racqspace.unattended_upgrades
    version: 2.1.10
  - src: systemli.bind9
    version: 1.5.0
  - name: k3s
    src: https://github.com/PyratLabs/ansible-role-k3s/archive/refs/tags/v3.4.4.tar.gz

collections:
  - name: ansible.posix
  - name: community.general
  - name: community.docker
  - name: community.postgresql
