---
name: Integration
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta
    paths-ignore:
      - ".*"
      - ".github/**"
      - "README.md"
  schedule:
    # * is a special character in YAML so you have to quote this string
    # first of each month
    - cron: "0 0 1 * *"

jobs:
  integration:
    name: Integration
    uses: systemli/github-ansible-workflow/.github/workflows/ansible-integration-workflow.yaml@v1.2.0
    with:
      distros: '[ "debian12", "debian11" ]'
